name: Deploy to Azure App Service

on:
  push:
    branches: [ "main" ]  # lub nazwa Twojego głównego brancha
  workflow_dispatch:  # pozwala uruchomić workflow ręcznie

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Logowanie do Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: twojrejestr.azurecr.io  # Zmień na nazwę Twojego rejestru
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Budowanie i publikowanie obrazu backendu
    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend  # katalog, gdzie znajduje się kod backendu
        file: ./backend/Dockerfile.backend  # ścieżka do Dockerfile dla backendu
        push: true
        tags: twojrejestr.azurecr.io/backend:${{ github.sha }}  # używamy SHA commita jako tag
    
    # Logowanie do Azure
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Wdrażanie backendu do Azure App Service
    - name: Deploy backend to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'twoja-aplikacja-backend'  # nazwa Twojego App Service dla backendu
        images: 'twojrejestr.azurecr.io/backend:${{ github.sha }}'
  
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend  # zapewnia, że backend zostanie wdrożony przed frontendem
    
    steps:
    - uses: actions/checkout@v3
    
    # Logowanie do Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: twojrejestr.azurecr.io  # Zmień na nazwę Twojego rejestru
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Budowanie i publikowanie obrazu frontendu
    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend  # katalog, gdzie znajduje się kod frontendu
        file: ./frontend/Dockerfile.frontend  # ścieżka do Dockerfile dla frontendu
        build-args: |
          VITE_API_URL=https://twoja-aplikacja-backend.azurewebsites.net
        push: true
        tags: twojrejestr.azurecr.io/frontend:${{ github.sha }}  # używamy SHA commita jako tag
    
    # Logowanie do Azure
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Wdrażanie frontendu do Azure App Service
    - name: Deploy frontend to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'twoja-aplikacja-frontend'  # nazwa Twojego App Service dla frontendu
        images: 'twojrejestr.azurecr.io/frontend:${{ github.sha }}'
